from enum import StrEnum

class Language(StrEnum):
    # Extracted from the HTML of the Commcare app settings page: https://www.commcarehq.org/a/givedirectly-hq/apps/view/{application_id}/settings/
    aar = "aar" # Afar
    abk = "abk" # Abkhazian
    ace = "ace" # Achinese
    ach = "ach" # Acoli
    ada = "ada" # Adangme
    ady = "ady" # Adyghe
    afa = "afa" # Afro-Asiatic languages
    afh = "afh" # Afrihili
    af = "af" # Afrikaans
    ain = "ain" # Ainu
    aka = "aka" # Akan
    akk = "akk" # Akkadian
    sqi = "sqi" # Albanian
    ale = "ale" # Aleut
    alg = "alg" # Algonquian languages
    alt = "alt" # Southern Altai
    amh = "amh" # Amharic
    anp = "anp" # Angika
    anu = "anu" # Anuak
    apa = "apa" # Apache languages
    ara = "ara" # Arabic
    arc = "arc" # Official Aramaic (700-300 BCE)
    arg = "arg" # Aragonese
    hye = "hye" # Armenian
    arn = "arn" # Mapudungun
    arp = "arp" # Arapaho
    art = "art" # Artificial languages
    arw = "arw" # Arawak
    asm = "asm" # Assamese
    ast = "ast" # Asturian
    ath = "ath" # Athapascan languages
    aus = "aus" # Australian languages
    ava = "ava" # Avaric
    ave = "ave" # Avestan
    awa = "awa" # Awadhi
    aym = "aym" # Aymara
    aze = "aze" # Azerbaijani
    bad = "bad" # Banda languages
    bai = "bai" # Bamileke languages
    bak = "bak" # Bashkir
    bal = "bal" # Baluchi
    bam = "bam" # Bambara
    ban = "ban" # Balinese
    eus = "eus" # Basque
    bas = "bas" # Basa
    bat = "bat" # Baltic languages
    bej = "bej" # Beja
    bel = "bel" # Belarusian
    bem = "bem" # Bemba
    ben = "ben" # Bengali
    ber = "ber" # Berber languages
    bho = "bho" # Bhojpuri
    bih = "bih" # Bihari languages
    bik = "bik" # Bikol
    bin = "bin" # Bini
    bis = "bis" # Bislama
    bla = "bla" # Siksika
    bnt = "bnt" # Bantu (Other)
    bos = "bos" # Bosnian
    bra = "bra" # Braj
    bre = "bre" # Breton
    btk = "btk" # Batak languages
    bua = "bua" # Buriat
    bug = "bug" # Buginese
    bul = "bul" # Bulgarian
    mya = "mya" # Burmese
    byn = "byn" # Blin
    cad = "cad" # Caddo
    cai = "cai" # Central American Indian languages
    car = "car" # Galibi Carib
    cat = "cat" # Catalan
    cau = "cau" # Caucasian languages
    ceb = "ceb" # Cebuano
    cel = "cel" # Celtic languages
    cha = "cha" # Chamorro
    chb = "chb" # Chibcha
    che = "che" # Chechen
    chg = "chg" # Chagatai
    zho = "zho" # Chinese
    chk = "chk" # Chuukese
    chm = "chm" # Mari
    chn = "chn" # Chinook jargon
    cho = "cho" # Choctaw
    chp = "chp" # Chipewyan
    chr = "chr" # Cherokee
    chv = "chv" # Chuvash
    chy = "chy" # Cheyenne
    cmc = "cmc" # Chamic languages
    cop = "cop" # Coptic
    cor = "cor" # Cornish
    cos = "cos" # Corsican
    cpe = "cpe" # Creoles and pidgins, English based
    cpf = "cpf" # Creoles and pidgins, French-based
    cpp = "cpp" # Creoles and pidgins, Portuguese-based
    cre = "cre" # Cree
    crh = "crh" # Crimean Tatar
    crp = "crp" # Creoles and pidgins
    csb = "csb" # Kashubian
    cus = "cus" # Cushitic languages
    ces = "ces" # Czech
    dag = "dag" # Dagbani
    dak = "dak" # Dakota
    dan = "dan" # Danish
    dar = "dar" # Dargwa
    day = "day" # Land Dayak languages
    delaware = "del" # Delaware - note: had to edit the attribute name bc del is a protected word in python
    den = "den" # Slave (Athapascan)
    dgr = "dgr" # Dogrib
    dyo = "dyo" # Diola
    din = "din" # Dinka
    div = "div" # Divehi
    doi = "doi" # Dogri
    dra = "dra" # Dravidian languages
    drs = "drs" # Gedeo
    dsb = "dsb" # Lower Sorbian
    dua = "dua" # Duala
    dum = "dum" # Dutch, Middle (ca.1050-1350)
    nld = "nld" # Dutch
    dyu = "dyu" # Dyula
    dzo = "dzo" # Dzongkha
    efi = "efi" # Efik
    egy = "egy" # Egyptian (Ancient)
    eka = "eka" # Ekajuk
    elx = "elx" # Elamite
    en = "en" # English
    epo = "epo" # Esperanto
    est = "est" # Estonian
    ewe = "ewe" # Ewe
    ewo = "ewo" # Ewondo
    fan = "fan" # Fang
    fao = "fao" # Faroese
    fat = "fat" # Fanti
    fij = "fij" # Fijian
    fil = "fil" # Filipino
    fin = "fin" # Finnish
    fiu = "fiu" # Finno-Ugrian languages
    fon = "fon" # Fon
    fra = "fra" # French
    frm = "frm" # French, Middle (ca.1400-1600)
    frr = "frr" # Northern Frisian
    frs = "frs" # Eastern Frisian
    fry = "fry" # Western Frisian
    fuc = "fuc" # Pulaar
    ful = "ful" # Fulah
    fur = "fur" # Friulian
    gaa = "gaa" # Ga
    gay = "gay" # Gayo
    gba = "gba" # Gbaya
    gem = "gem" # Germanic languages
    grt = "grt" # Garo
    kat = "kat" # Georgian
    kqy = "kqy" # Koore
    deu = "deu" # German
    gez = "gez" # Geez
    gil = "gil" # Gilbertese
    gla = "gla" # Gaelic
    gle = "gle" # Irish
    glg = "glg" # Galician
    glv = "glv" # Manx
    gmh = "gmh" # German, Middle High (ca.1050-1500)
    gon = "gon" # Gondi
    gor = "gor" # Gorontalo
    got = "got" # Gothic
    grb = "grb" # Grebo
    grc = "grc" # Greek, Ancient (to 1453)
    ell = "ell" # Greek, Modern (1453-)
    grn = "grn" # Guarani
    gsw = "gsw" # Swiss German
    guj = "guj" # Gujarati
    gwi = "gwi" # Gwich'in
    hai = "hai" # Haida
    hat = "hat" # Haitian
    hau = "hau" # Hausa
    haw = "haw" # Hawaiian
    heb = "heb" # Hebrew
    her = "her" # Herero
    hil = "hil" # Hiligaynon
    him = "him" # Himachali languages
    hin = "hin" # Hindi
    hit = "hit" # Hittite
    hmn = "hmn" # Hmong
    hmo = "hmo" # Hiri Motu
    hrv = "hrv" # Croatian
    hsb = "hsb" # Upper Sorbian
    hun = "hun" # Hungarian
    hup = "hup" # Hupa
    iba = "iba" # Iban
    ibo = "ibo" # Igbo
    isl = "isl" # Icelandic
    ido = "ido" # Ido
    iii = "iii" # Sichuan Yi
    ijo = "ijo" # Ijo languages
    iku = "iku" # Inuktitut
    ilb = "ilb" # Ila - Zambia
    ile = "ile" # Interlingue
    ilo = "ilo" # Iloko
    ina = "ina" # Interlingua (International Auxiliary Language Association)
    inc = "inc" # Indic languages
    ind = "ind" # Indonesian
    ine = "ine" # Indo-European languages
    inh = "inh" # Ingush
    ipk = "ipk" # Inupiaq
    ira = "ira" # Iranian languages
    iro = "iro" # Iroquoian languages
    ita = "ita" # Italian
    jav = "jav" # Javanese
    jbo = "jbo" # Lojban
    jpn = "jpn" # Japanese
    jpr = "jpr" # Judeo-Persian
    jrb = "jrb" # Judeo-Arabic
    kaa = "kaa" # Kara-Kalpak
    kab = "kab" # Kabyle
    kac = "kac" # Kachin
    kal = "kal" # Kalaallisut
    kam = "kam" # Kamba
    kan = "kan" # Kannada
    kar = "kar" # Karen languages
    kas = "kas" # Kashmiri
    kau = "kau" # Kanuri
    kaw = "kaw" # Kawi
    kaz = "kaz" # Kazakh
    kbd = "kbd" # Kabardian
    kha = "kha" # Khasi
    khi = "khi" # Khoisan languages
    khm = "khm" # Central Khmer
    kho = "kho" # Khotanese
    kik = "kik" # Kikuyu
    kin = "kin" # Kinyarwanda
    kir = "kir" # Kirghiz
    kmb = "kmb" # Kimbundu
    kok = "kok" # Konkani
    kom = "kom" # Komi
    kon = "kon" # Kongo
    kor = "kor" # Korean
    kos = "kos" # Kosraean
    kpe = "kpe" # Kpelle
    krc = "krc" # Karachay-Balkar
    kri = "kri" # Krio
    krl = "krl" # Karelian
    kro = "kro" # Kru languages
    kru = "kru" # Kurukh
    kua = "kua" # Kuanyama
    kum = "kum" # Kumyk
    kur = "kur" # Kurdish
    kut = "kut" # Kutenai
    lad = "lad" # Ladino
    lah = "lah" # Lahnda
    lam = "lam" # Lamba
    lao = "lao" # Lao
    lat = "lat" # Latin
    lav = "lav" # Latvian
    lez = "lez" # Lezghian
    lim = "lim" # Limburgan
    lin = "lin" # Lingala
    lit = "lit" # Lithuanian
    lol = "lol" # Mongo
    loz = "loz" # Lozi
    ltz = "ltz" # Luxembourgish
    lua = "lua" # Luba-Lulua
    lub = "lub" # Luba-Katanga
    lug = "lug" # Ganda
    lui = "lui" # Luiseno
    lun = "lun" # Lunda
    luo = "luo" # Luo (Kenya and Tanzania)
    lus = "lus" # Mizo
    lus = "lus" # Lushai
    mkd = "mkd" # Macedonian
    mad = "mad" # Madurese
    mag = "mag" # Magahi
    mah = "mah" # Marshallese
    mai = "mai" # Maithili
    mak = "mak" # Makasar
    mal = "mal" # Malayalam
    man = "man" # Mandingo
    mri = "mri" # Maori
    map = "map" # Austronesian languages
    mar = "mar" # Marathi
    mas = "mas" # Masai
    msa = "msa" # Malay
    mdf = "mdf" # Moksha
    mdr = "mdr" # Mandar
    men = "men" # Mende
    mga = "mga" # Irish, Middle (900-1200)
    mic = "mic" # Mi'kmaq
    min = "min" # Minangkabau
    mis = "mis" # Uncoded languages
    mkh = "mkh" # Mon-Khmer languages
    mlg = "mlg" # Malagasy
    mlt = "mlt" # Maltese
    mnc = "mnc" # Manchu
    mni = "mni" # Manipuri
    mno = "mno" # Manobo languages
    moh = "moh" # Mohawk
    mon = "mon" # Mongolian
    mos = "mos" # Mossi
    mul = "mul" # Multiple languages
    mun = "mun" # Munda languages
    mus = "mus" # Creek
    mwl = "mwl" # Mirandese
    mwr = "mwr" # Marwari
    myn = "myn" # Mayan languages
    myv = "myv" # Erzya
    nah = "nah" # Nahuatl languages
    nai = "nai" # North American Indian languages
    nap = "nap" # Neapolitan
    nau = "nau" # Nauru
    nav = "nav" # Navajo
    nbl = "nbl" # Ndebele, South
    nde = "nde" # Ndebele, North
    ndo = "ndo" # Ndonga
    nds = "nds" # Low German
    nep = "nep" # Nepali
    new = "new" # Nepal Bhasa
    nia = "nia" # Nias
    nic = "nic" # Niger-Kordofanian languages
    niu = "niu" # Niuean
    nno = "nno" # Norwegian Nynorsk
    nob = "nob" # Bokml, Norwegian
    nog = "nog" # Nogai
    nor = "nor" # Norwegian
    nqo = "nqo" # N'Ko
    nso = "nso" # Pedi
    nub = "nub" # Nubian languages
    nus = "nus" # Nuer
    nya = "nya" # Chichewa
    nym = "nym" # Nyamwezi
    nyn = "nyn" # Nyankole
    nyo = "nyo" # Nyoro
    nzi = "nzi" # Nzima
    oci = "oci" # Occitan (post 1500)
    oji = "oji" # Ojibwa
    ori = "ori" # Oriya
    orm = "orm" # Oromo
    osa = "osa" # Osage
    oss = "oss" # Ossetian
    ota = "ota" # Turkish, Ottoman (1500-1928)
    oto = "oto" # Otomian languages
    paa = "paa" # Papuan languages
    pag = "pag" # Pangasinan
    pal = "pal" # Pahlavi
    pam = "pam" # Pampanga
    pan = "pan" # Panjabi
    pap = "pap" # Papiamento
    pau = "pau" # Palauan
    fas = "fas" # Persian
    phi = "phi" # Philippine languages
    phn = "phn" # Phoenician
    pli = "pli" # Pali
    pol = "pol" # Polish
    pon = "pon" # Pohnpeian
    por = "por" # Portuguese
    pra = "pra" # Prakrit languages
    pus = "pus" # Pushto
    qaa-qtz = "qtz" # Reserved for local use
    que = "que" # Quechua
    raj = "raj" # Rajasthani
    rap = "rap" # Rapanui
    rar = "rar" # Rarotongan
    roa = "roa" # Romance languages
    roh = "roh" # Romansh
    rom = "rom" # Romany
    ron = "ron" # Romanian
    run = "run" # Rundi
    rup = "rup" # Aromanian
    rus = "rus" # Russian
    sad = "sad" # Sandawe
    sag = "sag" # Sango
    sah = "sah" # Yakut
    sai = "sai" # South American Indian (Other)
    sal = "sal" # Salishan languages
    sam = "sam" # Samaritan Aramaic
    san = "san" # Sanskrit
    sas = "sas" # Sasak
    sat = "sat" # Santali
    scn = "scn" # Sicilian
    sco = "sco" # Scots
    sel = "sel" # Selkup
    sem = "sem" # Semitic languages
    sgn = "sgn" # Sign Languages
    shn = "shn" # Shan
    sid = "sid" # Sidamo
    sin = "sin" # Sinhala
    sio = "sio" # Siouan languages
    sit = "sit" # Sino-Tibetan languages
    sla = "sla" # Slavic languages
    slk = "slk" # Slovak
    slv = "slv" # Slovenian
    sma = "sma" # Southern Sami
    sme = "sme" # Northern Sami
    smi = "smi" # Sami languages
    smj = "smj" # Lule Sami
    smn = "smn" # Inari Sami
    smo = "smo" # Samoan
    sms = "sms" # Skolt Sami
    sna = "sna" # Shona
    snd = "snd" # Sindhi
    snk = "snk" # Soninke
    sog = "sog" # Sogdian
    som = "som" # Somali
    son = "son" # Songhai languages
    sot = "sot" # Sotho, Southern
    es = "es" # Spanish
    srd = "srd" # Sardinian
    srn = "srn" # Sranan Tongo
    srp = "srp" # Serbian
    srr = "srr" # Serer
    ssa = "ssa" # Nilo-Saharan languages
    ssw = "ssw" # Swati
    suk = "suk" # Sukuma
    sun = "sun" # Sundanese
    sus = "sus" # Susu
    sux = "sux" # Sumerian
    sw = "sw" # Swahili
    swe = "swe" # Swedish
    syc = "syc" # Classical Syriac
    syr = "syr" # Syriac
    tah = "tah" # Tahitian
    tai = "tai" # Tai languages
    tam = "tam" # Tamil
    tat = "tat" # Tatar
    tdx = "tdx" # Tandroy-Mafahaly
    tel = "tel" # Telugu
    tem = "tem" # Timne
    ter = "ter" # Tereno
    tet = "tet" # Tetum
    tgk = "tgk" # Tajik
    tgl = "tgl" # Tagalog
    tha = "tha" # Thai
    bod = "bod" # Tibetan
    tig = "tig" # Tigre
    tir = "tir" # Tigrinya
    tiv = "tiv" # Tiv
    tkl = "tkl" # Tokelau
    tlh = "tlh" # Klingon
    tli = "tli" # Tlingit
    tmh = "tmh" # Tamashek
    tog = "tog" # Tonga (Nyasa)
    ton = "ton" # Tonga (Tonga Islands)
    tpi = "tpi" # Tok Pisin
    tsi = "tsi" # Tsimshian
    tsn = "tsn" # Tswana
    tso = "tso" # Tsonga
    tuk = "tuk" # Turkmen
    tum = "tum" # Tumbuka
    tup = "tup" # Tupi languages
    tur = "tur" # Turkish
    tut = "tut" # Altaic languages
    tvl = "tvl" # Tuvalu
    twi = "twi" # Twi
    tyv = "tyv" # Tuvinian
    udm = "udm" # Udmurt
    uga = "uga" # Ugaritic
    uig = "uig" # Uighur
    ukr = "ukr" # Ukrainian
    umb = "umb" # Umbundu
    und = "und" # Undetermined
    urd = "urd" # Urdu
    uzb = "uzb" # Uzbek
    vai = "vai" # Vai
    ven = "ven" # Venda
    vie = "vie" # Vietnamese
    vol = "vol" # Volapk
    vot = "vot" # Votic
    wak = "wak" # Wakashan languages
    wal = "wal" # Wolaytta
    war = "war" # Waray
    was = "was" # Washo
    cym = "cym" # Welsh
    wen = "wen" # Sorbian languages
    wln = "wln" # Walloon
    wol = "wol" # Wolof
    xal = "xal" # Kalmyk
    xho = "xho" # Xhosa
    yao = "yao" # Yao
    yap = "yap" # Yapese
    yid = "yid" # Yiddish
    yor = "yor" # Yoruba
    ypk = "ypk" # Yupik languages
    zap = "zap" # Zapotec
    zbl = "zbl" # Blissymbols
    zen = "zen" # Zenaga
    zha = "zha" # Zhuang
    znd = "znd" # Zande languages
    zul = "zul" # Zulu
    zun = "zun" # Zuni
    zxx = "zxx" # No linguistic content
    zza = "zza" # Zaza